package org.searlelab.context.percolator;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.util.Arrays;
import java.util.List;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.searlelab.context.percolator.PercolatorWeights;

public class PercolatorWeightsTest {
	private static final double EPSILON = 1e-9;

	@Rule
	public TemporaryFolder folder = new TemporaryFolder();

	@Test
	public void averagesRawWeightsAcrossCrossValidationBins() throws IOException {
		File weights = write("weights.txt",
				"featA\tfeatB\tm0",
				"0.5\t0.5\t0.5",
				"1.0\t2.0\t-1.0",
				"featA\tfeatB\tm0",
				"0.1\t0.1\t0.1",
				"3.0\t4.0\t1.0");

		PercolatorWeights model = PercolatorWeights.parse(weights);

		assertEquals(Arrays.asList("featA", "featB"), model.getFeatureNames());
		assertEquals(2, model.getNumberOfBins());
		assertEquals(2.0, model.getWeights()[0], EPSILON);
		assertEquals(3.0, model.getWeights()[1], EPSILON);
		assertEquals(0.0, model.getBias(), EPSILON);
	}

	@Test
	public void handlesTwoLinesPerBin() throws IOException {
		File weights = write("weights.txt",
				"featA\tm0",
				"2.0\t1.0",
				"featA\tm0",
				"4.0\t3.0");

		PercolatorWeights model = PercolatorWeights.parse(weights);

		assertEquals(2, model.getNumberOfBins());
		assertEquals(3.0, model.getWeights()[0], EPSILON);
		assertEquals(2.0, model.getBias(), EPSILON);
	}

	@Test
	public void scoreIsTheDotProductPlusBias() throws IOException {
		File weights = write("weights.txt",
				"featA\tfeatB\tm0",
				"0.0\t0.0\t0.0",
				"2.0\t3.0\t-1.0");

		PercolatorWeights model = PercolatorWeights.parse(weights);

		assertEquals(2.0 * 4.0 + 3.0 * 5.0 - 1.0, model.score(new double[] { 4.0, 5.0 }), EPSILON);
	}

	@Test
	public void ignoresBlankAndCommentLines() throws IOException {
		File weights = write("weights.txt",
				"# generated by percolator",
				"featA\tm0",
				"",
				"1.0\t0.0",
				"2.0\t4.0");

		PercolatorWeights model = PercolatorWeights.parse(weights);

		assertEquals(1, model.getNumberOfBins());
		assertEquals(2.0, model.getWeights()[0], EPSILON);
		assertEquals(4.0, model.getBias(), EPSILON);
	}

	@Test
	public void rejectsWeightRowsThatDoNotMatchTheirHeader() throws IOException {
		File weights = write("weights.txt",
				"featA\tfeatB\tm0",
				"1.0\t2.0");

		try {
			PercolatorWeights.parse(weights);
			fail("expected a parse failure when a weights row is the wrong width");
		} catch (IOException expected) {
			assertTrue(expected.getMessage().contains("features"));
		}
	}

	@Test
	public void rejectsBinsThatNameDifferentFeatures() throws IOException {
		File weights = write("weights.txt",
				"featA\tm0",
				"1.0\t0.0",
				"featB\tm0",
				"1.0\t0.0");

		try {
			PercolatorWeights.parse(weights);
			fail("expected a parse failure when CV bins disagree on feature names");
		} catch (IOException expected) {
			assertTrue(expected.getMessage().contains("different features"));
		}
	}

	@Test
	public void rejectsAnEmptyWeightsFile() throws IOException {
		try {
			PercolatorWeights.parse(write("weights.txt"));
			fail("expected a parse failure for an empty weights file");
		} catch (IOException expected) {
			assertTrue(expected.getMessage().contains("no weights"));
		}
	}

	@Test
	public void writesTheAveragedModelWithABiasRow() throws IOException {
		File weights = write("weights.txt",
				"featA\tfeatB\tm0",
				"0.0\t0.0\t0.0",
				"1.0\t2.0\t3.0");

		File averaged = new File(folder.getRoot(), "averaged.tsv");
		PercolatorWeights.parse(weights).writeAveraged(averaged);

		List<String> lines = Files.readAllLines(averaged.toPath());
		assertEquals(4, lines.size());
		assertEquals("feature\tweight", lines.get(0));
		assertTrue(lines.get(1).startsWith("featA\t"));
		assertTrue(lines.get(2).startsWith("featB\t"));
		assertTrue(lines.get(3).startsWith("__bias__\t"));
	}

	private File write(String name, String... lines) throws IOException {
		File file = folder.newFile(name);
		try (PrintWriter out = new PrintWriter(file, "UTF-8")) {
			for (String line : lines) {
				out.println(line);
			}
		}
		return file;
	}
}
